ports:
  - port: 5000
    onOpen: open-preview
    description: Flask App preview

tasks:
  - init: |
      export FLASK_APP=flaskr
      export FLASK_ENV=development
      pip install -r requirements.txt
      
  - command: |
      flask run